version: '3'
services:
  nginx: 
    image: nginx:1.14.2
    restart: always
    volumes: 
      - ./code:/code
      - ./nginx/conf:/etc/nginx
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443

  php:
    image: php:7.3.4-fpm
    restart: always
    volumes:
      - ./code:/code

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: test 
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  redis:
    image: redis:5.0.3
    restart: always
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
